### ISSUE TITLE
Problem with UTF8

### ISSUE THREAD

**Issue by jakub-olczyk** [conchyliculture/wikipoff-tools#6]
I tried converting Polish Wikipedia dump:
```
jakub@debian:wikipoff-tools$ python WikiConverter.py ~/Pobrane/plwiki-20170520-pages-articles.xml.bz2 pl.wiki.sqlite
Traceback (most recent call last):
  File "WikiConverter.py", line 152, in <module>
    main()
  File "WikiConverter.py", line 146, in main
    wikiextractor = WikiDoStuff(args.xml_file, args.output_file)
  File "WikiConverter.py", line 27, in __init__
    self.xml_extractor = XMLworker(input_file)
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/XMLworker.py", line 17, in __init__
    self.db_metadata = self._GetInfos()
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/XMLworker.py", line 54, in _GetInfos
    line = fd.readline().decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb0 in position 10: invalid start byte
```

I assume the problem is with the encoding of the dump itself. Is there any way I could help with resolving of the issue? Since the official Wikipedia App doesn't support Android in 4.1 version I wanted to use your app instead ;)

**Comment by conchyliculture** [comment]
Can you try to bunzip the dump first ? And then run the script on the XML file:

`python WikiConverter.py ~/Pobrane/plwiki-20170520-pages-articles.xml pl.wiki.sqlite`

**Comment by jakub-olczyk** [comment]
OK I bunzipped it ;) Seems to do the trick... but I guess that #4 is still a valid issue
```
jakub@debian:wikipoff-tools$ python WikiConverter.py ~/Pobrane/plwiki-20170520-pages-articles.xml pl.wiki.sqlite
Converting xml dump /home/jakub/Pobrane/plwiki-20170520-pages-articles.xml to database pl.wiki.sqlite. This may take eons...
Process Worker-0: | Compressing \ | Results Queue Size:      1
Process Worker-1:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Worker-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Worker-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Worker-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Worker-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "WikiConverter.py", line 103, in WorkerTask
  File "WikiConverter.py", line 103, in WorkerTask
    self.run()
    self.run()
    self.run()
    self.run()
    message_json[u'title'], message_json[u'body'])
    message_json[u'title'], message_json[u'body'])
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/converter.py", line 150, in Convert
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/converter.py", line 150, in Convert
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "WikiConverter.py", line 103, in WorkerTask
  File "WikiConverter.py", line 103, in WorkerTask
  File "WikiConverter.py", line 103, in WorkerTask
  File "WikiConverter.py", line 103, in WorkerTask
    message_json[u'title'], message_json[u'body'])
    message_json[u'title'], message_json[u'body'])
    message_json[u'title'], message_json[u'body'])
    message_json[u'title'], message_json[u'body'])
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/converter.py", line 150, in Convert
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/converter.py", line 150, in Convert
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/converter.py", line 150, in Convert
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/converter.py", line 150, in Convert
    text = self._Clean(text)
    text = self._Clean(text)
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/converter.py", line 161, in _Clean
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/converter.py", line 161, in _Clean
    text = self.translator.Translate(input_text)
    text = self.translator.Translate(input_text)
    text = self._Clean(text)
    text = self._Clean(text)
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/languages/wikifr.py", line 103, in Translate
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/languages/wikifr.py", line 103, in Translate
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/converter.py", line 161, in _Clean
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/converter.py", line 161, in _Clean
    text = self.translator.Translate(input_text)
    text = self.translator.Translate(input_text)
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/languages/wikifr.py", line 103, in Translate
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/languages/wikifr.py", line 103, in Translate
    text = self._Clean(text)
    text = self._Clean(text)
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/converter.py", line 161, in _Clean
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/converter.py", line 161, in _Clean
    text = self.translator.Translate(input_text)
    text = self.translator.Translate(input_text)
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/languages/wikifr.py", line 103, in Translate
  File "/home/jakub/workbench/wikipoff-tools/lib/wikimedia/languages/wikifr.py", line 103, in Translate
    locale.setlocale(locale.LC_ALL, u'fr_FR.utf-8')
    locale.setlocale(locale.LC_ALL, u'fr_FR.utf-8')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    locale.setlocale(locale.LC_ALL, u'fr_FR.utf-8')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    locale.setlocale(locale.LC_ALL, u'fr_FR.utf-8')
    locale.setlocale(locale.LC_ALL, u'fr_FR.utf-8')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    locale.setlocale(locale.LC_ALL, u'fr_FR.utf-8')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
    return _setlocale(category, locale)
Error: unsupported locale setting
Error: unsupported locale setting
    return _setlocale(category, locale)
    return _setlocale(category, locale)
    return _setlocale(category, locale)
    return _setlocale(category, locale)
Error: unsupported locale setting
Error: unsupported locale setting
Error: unsupported locale setting
Error: unsupported locale setting
```
The Workers have failed due to locale setting.

**Comment by jakub-olczyk** [comment]
Maybe adding an option to the invocation of the script could do the trick?

**Comment by jakub-olczyk** [comment]
I have installed the FR.UTF-8 locale and the generation have started.

**Comment by conchyliculture** [comment]
Could you re-try without the FR.UTF-8 locale, and the following patch:
```
diff --git lib/wikimedia/wikitools.py lib/wikimedia/wikitools.py
index f7f34e0..c6ea077 100644
--- lib/wikimedia/wikitools.py
+++ lib/wikimedia/wikitools.py
@@ -1,9 +1,10 @@
 # -*- coding: utf-8 -*-
 
-from lib.wikimedia.languages import *
+from lib.wikimedia.languages import wikien
 
 def GetLanguageModule(wikitype, wikilang):
     if wikitype == u'wikipedia':
         if wikilang == u'fr':
+            from lib.wikimedia.languages import wikifr
             return wikifr.WikiFRTranslator()
     return wikien.WikiEnTranslator()
```

**Comment by conchyliculture** [comment]
Commit 49a4b64df06eb5afc16c3c9fdb2c23bf56d5d597 should fix the locale issule
